version: '3.9'

services:
  fcg-db-central:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    restart: unless-stopped 
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_db_fcg_central:/var/opt/mssql/data
    networks:
      - fcg-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fcg-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
  redis:
    image: redis:7-alpine  
    command: redis-server --appendonly yes --requirepass ${REDIS_SA_PASSWORD}
    container_name: redis-fcg
    restart: unless-stopped 
    ports:
      - "6379:6379"
    networks:
      - fcg-network
    volumes:
      - redis_data:/var/lib/redis
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-fcg
    restart: unless-stopped 
    ports:
      - "8001:5540"
    networks:
      - fcg-network
  users-db-migration:
    image: alexoliverdev/fcg-usuario-api:latest
    container_name: fcg-users-db-migration
    depends_on:
      fcg-db-central:
        condition: service_healthy
    environment:
      - ConnectionStrings__UserConnection=Server=fcg-db-central;Database=Fcg_Users;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    entrypoint: ["./efbundle", "--connection", "Server=fcg-db-central;Database=Fcg_Users;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"]
    networks:
      - fcg-network

  users-api:
    image: alexoliverdev/fcg-usuario-api:latest
    container_name: fcg-users-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMq=rabbitmq
      - ConnectionStrings__UserConnection=Server=fcg-db-central;Database=Fcg_Users;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - JwtSettings__Secret=${JWT_SECRET}  
    depends_on:
      fcg-db-central:
        condition: service_healthy 
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      users-db-migration:
        condition: service_completed_successfully
    networks:
      - fcg-network

  notifications-api:
    image: alexoliverdev/fcg-notification-api:latest
    container_name: fcg-notifications-api
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMq=rabbitmq    
    depends_on:
      - rabbitmq
      - redis
      - users-api
    networks:
      - fcg-network

  payments-db-migration:
    image: alexoliverdev/fcg-payments-api:latest
    container_name: fcg-payments-db-migration
    depends_on:
      fcg-db-central:
        condition: service_healthy
    environment:
      - ConnectionStrings__PaymentConnection=Server=fcg-db-central;Database=Fcg_Payments;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    entrypoint: ["./efbundle", "--connection", "Server=fcg-db-central;Database=Fcg_Payments;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"]
    networks:
      - fcg-network

  payments-api:
    image: alexoliverdev/fcg-payments-api:latest  
    container_name: fcg-payments-api
    ports:
      - "8083:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__RabbitMq=rabbitmq
     - ConnectionStrings__PaymentConnection=Server=fcg-db-central;Database=Fcg_Payments;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;  
    depends_on:
      fcg-db-central:
        condition: service_healthy 
      rabbitmq:
        condition: service_started
      catalog-api:
        condition: service_started
      payments-db-migration:
        condition: service_completed_successfully
    networks:
      - fcg-network

  catalog-db-migration:
    image: alexoliverdev/fcg-catalog-api:latest
    container_name: fcg-catalog-db-migration
    depends_on:
      fcg-db-central:
        condition: service_healthy
    environment:
      - ConnectionStrings__CatalogConnection=Server=fcg-db-central;Database=Fcg_Catalogs;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    entrypoint: ["./efbundle", "--connection", "Server=fcg-db-central;Database=Fcg_Catalogs;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"]
    networks:
      - fcg-network

  catalog-api:
    image: alexoliverdev/fcg-catalog-api:latest
    container_name: fcg-catalog-api
    ports:
      - "8084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RabbitMq=rabbitmq
      - ConnectionStrings__CatalogConnection=Server=fcg-db-central;Database=Fcg_Catalogs;User Id=sa; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;  
      - JwtSettings__Secret=${JWT_SECRET}  
    depends_on:
      fcg-db-central:
        condition: service_healthy 
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      users-api:
        condition: service_started
      catalog-db-migration:
        condition: service_completed_successfully
    networks:
      - fcg-network


volumes:
  sql_db_fcg_central:
  rabbitmq_data:
  redis_data:

networks:
  fcg-network:
    driver: bridge