apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-payment-api-deployment
  labels:
    app: fcg-payment-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fcg-payment-api
  template:
    metadata:
      labels: 
        app: fcg-payment-api
      annotations:
        autor: Alex O Ferreira
        description: "Deployment do microsservico de Pagamentos API do Fiap Cloud Games"
    spec:
      initContainers:
      - name: c-payments-db-migration
        image: alexoliverdev/fcg-payments-api:latest  
        command: ["./efbundle"]   
        env:
          - name: DatabaseSettings__Host
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: DB_SERVER
          - name: DatabaseSettings__Port
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: DB_PORT
          - name: DatabaseSettings__DatabaseName
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: DB_NAME
          - name: DatabaseSettings__Username
            valueFrom:
              secretKeyRef:
                name: payment-opaque
                key: DB_USER
          - name: DatabaseSettings__Password
            valueFrom:
              secretKeyRef:
                name: payment-opaque
                key: DB_PASS                 
      containers:
      - name: c-fcg-payments-api
        image:  alexoliverdev/fcg-payments-api:latest  
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        env:
          - name: RabbitMqSettings__Host
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: RABBITMQ_SERVER
          - name: RabbitMqSettings__Port
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: RABBITMQ_PORT
          - name: RabbitMqSettings__Username
            valueFrom:
              secretKeyRef:
                name: payment-opaque
                key: RABBITMQ_USER
          - name: RabbitMqSettings__Password
            valueFrom:
              secretKeyRef:
                name: payment-opaque
                key: RABBITMQ_PASS
          - name: RabbitMqSettings__PaymentOrderQueue
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: PAYMENT_ORDER_QUEUE
          - name: RabbitMqSettings__PaymentDeliveryFailedQueue
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: PAYMENT_DELIVERY_FAILED_QUEUE
          - name: DatabaseSettings__Host
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: DB_SERVER
          - name: DatabaseSettings__DatabaseName
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: DB_NAME
          - name: DatabaseSettings__Port
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: DB_PORT          
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: ENVIRONMENT          
          - name: DatabaseSettings__Username
            valueFrom:
              secretKeyRef:
                name: payment-opaque
                key: DB_USER
          - name: DatabaseSettings__Password
            valueFrom:
              secretKeyRef:
                name: payment-opaque
                key: DB_PASS 
          - name: K8S_MASSTELEMETRY
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: MASSTRANSIT_USAGE_TELEMETRY                             
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5