apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-redis
  template:
    metadata:
      labels:
        app: db-redis
    spec:
      containers:      
      - name: c-redis
        image: redis:7-alpine         
        command: ["sh", "-c", "redis-server --appendonly yes --requirepass $REDIS_PASSWORD"]
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-opaque
                key: redis_pass
        ports:
          - containerPort: 6379                
        livenessProbe:
          exec:
            command: ["sh", "-c", "redis-cli -a $REDIS_PASSWORD ping"]
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["sh", "-c", "redis-cli -a $REDIS_PASSWORD ping"]
          initialDelaySeconds: 5
          periodSeconds: 5          
        volumeMounts: 
          - name: redis-storage
            mountPath: /data       
      - name: c-redisinsight
        image: redis/redisinsight:latest
        ports:
          - containerPort: 5540 
        env:
          - name: K8S_REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: REDIS_HOST
          - name: K8S_REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: REDIS_PORT
          - name: K8S_REDIS_INSTANCE
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: REDIS_INSTANCE
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-data-pvc